# Generated by Django 4.2.1 on 2023-06-11 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('', 'Niente...'), (1, 'Disgustoso!'), (2, 'Brutto!'), (3, 'Bene!'), (4, 'Eccellente!'), (5, 'Fantastico!')], default=0),
        ),
    ]
