# Generated by Django 4.2.1 on 2023-06-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_review_menu_item_alter_review_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
    ]
